### ISSUE TITLE
Проблема мертвого клиента

### ISSUE THREAD

**Issue by droganov** [derbyparty/derby-faq#37]
Привет.
Есть еще такая проблема. Вечером оставляю открытую вкладку с дерби-приложением, а утром нахожу ~~труп~~ запись в консоли: `Failed to load resource: net::ERR_CACHE_MISS`

А если покликать по ссылкам, то меняется только адресная строка, а рендер не происходит.

В консоли после такого клика появилось: ` WebSocket: connection is broken CloseEvent {reason: "", code: 1006, wasClean: false, clipboardData: undefined, path: NodeList[0]…}`

Это проблема самого дерби или проблема его конфигурации? Хочется сделать, так, чтобы он по возможности сам восстанавливал соединение.

**Comment by droganov** [comment]
Артур, вот проблемное место:

```
Socket.prototype._getTimeout = function(){
var base = this._options.timeout;
var increment = this._options.timeoutIncrement * this._attemptNum;
return  base + increment;
};
```

Прежде чем предлагать патч, хочу обсудить.
Думаю что:

1. таймаут реконнекта не следует увеличивать бесконечно, потолка 3 секунды вполне достаточно:  `return  Math.min(base + increment, 3000)`

2. Если по неизвестным мне причинам нужен более долгий таймаут, то нужно добавить попытку коннекта по пользовательским событиям (фокус окна, маусмув, скролл). То есть когда нет коннекта, но известно, что пользователь взаимодействует с приложением.

Что скажете?

**Comment by zag2art** [comment]
Думаю 3000 тоже можно в опции вынести, и 3000 установить по-дефолту. А так, я не против.

**Comment by droganov** [comment]
Опции в сервере задаются?

**Comment by zag2art** [comment]
Ага, https://github.com/derbyparty/racer-highway/blob/master/lib/server.js#L11

**Comment by droganov** [comment]
Хм, там 10000 а не 3000 это обычный таймаут. Пока ничего не буду патчить потестируем локально. Нужно к событиям видимо привязывать, заставлять пользователя ждать не стоит.
