### ISSUE TITLE
Можно ли получить в компоненте документ по remote пути?

### ISSUE THREAD

**Issue by LeoMoroz** [derbyparty/derby-faq#38]
Разъясните мне, пожалуйста, такой нюанс. Можно ли в компоненте таким образом обращаться по remote пути, чтобы получить синхронизированный с db документ?
```javascript
app.get('home', '/');

app.component('new', New)

function New() {};

New.prototype.create = function(model) {
  var item = model.root.at('items.1');
  model.subscribe(item, function (err) {
    item.set({text: "Hello world"});
  });
}
```

**Comment by zag2art** [comment]
Да можно, хотя считается, что подписываться н данные в компоненте - антипаттерн.

**Comment by zag2art** [comment]
Обычная, если надо в компонентах работать с remote документами, мы делаем так:

1. подписываемя на эти документы в роут-контроллере. Допустим на коллекцию `items`
2. потом пробрасываем в init-е компонента путь, делая его локальным:
```js
New.prototype.init = function(){
  this.items = this.model.scope('items');
  this.model.ref 'items', this.items;
}
```
Далее во вьюхе компонента можно писать просто `items` вместо `#root.items` ну и во всех остальных функция компонента можно использовать `this.items` для получения доступа к этой коллекции, например, так: `var id1 = this.items.get('id1')`

**Comment by zag2art** [comment]
Или основная задача все-таки подписаться на внешний документ?

**Comment by ivanchern** [comment]
Привет, Артур! На хабре почитал твои уроки и пошел осваивать Derby. Спасибо тебе огромное! Вот сейчас тоже задался вопросом где лучше подписываться - в компоненте или контроллере. Теперь все понятно.
В принципе, логично подписываться в роут-контроллере, тем более данные редко бывают нужны только в одном компоненте. А как правильнее поступать: передавать данные в компонент через атрибуты явно или в ```init``` обращаться к ```root``` области?
Спасибо!

**Comment by zag2art** [comment]
Здесь надо добавить, что для мы каждую страницу тоже делаем компонентом. То-есть у нас, как бы есть 2 вида компонентов: компоненты-страницы и обычные компоненты. В  компонентах страницах мы в `init`-е прописываем все глобальные зависимости через scope и пробрасываем их внутрь скоупа компоненты (как я показал выше). В обычные компоненты мы передаем все все через атрибуты и не используем root, чтобы уменьшить связанность.

**Comment by balek** [comment]
Почему вы никак не отразили этот подход в derby-router? Мне кажется оно прям напрашивается - сделать костыль сшивающий роутинг, подписки и компоненты. Я свой сделал.) Я описываю словарём все query и документы, на них автоматически создаётся подписка и делается проброс в компоненту, заодно создаются соответствующие аттрибуты у this. Как только начал использовать дерби, сразу начал раздражать boilerplate. Сначала кое-как сделал эту штуку, теперь по-тихоньку допиливаю.

**Comment by zag2art** [comment]
Покажи пример какой-нибудь простенький, чтобы понятно было, а то я че-то сходу не въезжаю (может с утра). Если идея достаточно "общая" и интересная - может и в роутер прикрутим.

**Comment by balek** [comment]
<code>
app.get '/chats/:chat', ClassyController app,

    name: 'chat'

    title: -> 'Чат'

    # $model описывает все действия с моделью, которые нужно выполнить перед рендерингом
    # Может быть объектом, функцией возвращающей объект, или массивом из объектов/функций

    $model: [ # Массив используется, когда нужны вложенные подписки
        -> # Первый subscribe. Это у меня такая паджинация, сначала запрашиваем n-ое сообщение...
            user: # Подписка по path
                 'users.' + @model.get '_session.userId'
            firstSubscriptionMessage: # Подписка на query
                $collection: 'messages'
                $serverQuery: 'firstSubscriptionMessage'
                chat: @params.chat
        -> # Вложенный subscribe использует результат первого. Подписываемся на все сообщения, начиная с n-го.
            messages:
                $collection: 'messages'
                $serverQuery: 'chat'
                chat: @params.chat
                startDate: @firstSubscriptionMessage.get()?[0]?.date or ''
    ]

    # Дальше идут методы компоненты
    sendText: ->
        # Описанные в $model вещи доступны в this
        @user.get()
        @messages.get()
</code>

Хотелось бы из этого и derby-router прийти к чему-то похожему на angular-ui-router. Пока руки не доходят просто.
Классно, кстати, было бы scope компоненты-страницы подменить на _page. Но я сколько ни пытался сделать такой хак, у меня не получилось.

**Comment by cray0000** [comment]
@balek как раз что-то похожее и хотели сделать. Идея объединить компонент-страницу и обработчик роута давно была, вопрос в том как сделать хорошее API, чтобы покрыть как минимум распространенные варианты использования. Декларативный вариант со словарем подписок выглядит довольно хорошо. 

Идея с подменой скоупа компонента на `_page` впринципе осуществима, как минимум можно захакать конструктор компонента и сделать чтобы он не в `$components._N` локальную модель создавал, а в `_page`. При этом и очистка должно нормально проходить, так как время жизни компонента-страницы должно быть идентичным времени жизни Page.

**Comment by balek** [comment]
Да, этот декларативный вариант мне кажется очень удобным. Особенно в сочетании с кофескриптом. Я таким же образом делаю ещё и model.ref, и model.set, и фильтры накладываю. В планах ещё сделать опциональный "лёгкий" ре-рендеринг страницы: когда на клиенте осуществляется переход на тот же самый роут, можно обновить подписки с новым `params` и не вызывать `page.render`. В общем, тоже, что можно сделать с помощью transitional routes, но без кода, автоматически.
