### ISSUE TITLE
setTimeout()  in Derbyjs

### ISSUE THREAD

**Issue by paradoxina** [derbyparty/derby-faq#39]
Расскажите пожалуйста как работают таймеры в Derbyjs и как правильно с ними работать. Как запустить таймер на сервере и на клиенте одновременно, как по отдельности, или там или там. Как правильно запустить таймер из реактивной функции на сервере. Буду благодарен за ответ.

**Comment by zag2art** [comment]
Опишите подробней ситуацию, чего вы хотите добиться, для чего вам таймеры? Иначе не понятно. А так, если абстрагироваться, то setTimeout работает и на сервере и на клиенте, абсолютно так же, как и без дерби, он же не является частью фреймворка. В реактивных функциях использовать setTimeout бессмысленно, потому что они синхронные...

Поэтому я и говорю - опишите задачу, а я подскажу вам, как бы я ее решил, используя дерби.

**Comment by paradoxina** [comment]
задача: запускать кучу таймеров на сервере, запускать должны клиенты, (то есть таймеры должны работать и выполнять код на сервере, независимо от того есть ли клиент в онлайне или вышел). Насколько я знаю node работает с таймерами по особому.  Проще говоря, клиент заходит на сайт, нажимает кнопку "записать" и выходит, спустя определенное время сервер перезаписывает базу данных,  клиент может передумать и зайти до того как данные запишутся и отменить. В app.proto.myfn таймеры срабатываю только на клиенте, в app.ini и на клиенте и на сервере. Я в этом деле новичок, и хочется знать как мне код выполнять строго на сервере, а как только на клиенте. Благодарю за ответ

**Comment by zag2art** [comment]
Для подобной задачи я бы использовал [node-cron](https://github.com/ncb000gt/node-cron) на сервере. Для хранения задач, я бы завел коллекцию tasks, при старте задачи клиентом записывал бы ее в эту коллекцию, на сервере бы ловил эту запись при помощи [derby-hook](https://www.npmjs.com/package/derby-hook). В задаче хранил бы ее статус и id-юзера, так чтобы ее всегда можно было отменить и возобновить на случай перезагрузки сервера.

**Comment by paradoxina** [comment]
я вас понял, это то что нужно, а все таки хочется узнать как запустить таймер из клиента на сервере, я понимаю что он исчезнет при перезапуске сервера

**Comment by zag2art** [comment]
Ну, например, в простейшем варианте, при момощи [этого](https://github.com/derbyparty/derby-faq/tree/master/ru#%D0%9C%D0%BD%D0%B5-%D0%BD%D1%83%D0%B6%D0%BD%D0%BE-%D1%87%D0%B0%D1%81%D1%82%D1%8C-%D0%BA%D0%BE%D0%B4%D0%B0-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D1%8F%D1%82%D1%8C-%D1%81%D1%82%D1%80%D0%BE%D0%B3%D0%BE-%D0%BD%D0%B0-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%B5-%D0%B5%D1%81%D1%82%D1%8C-%D0%BB%D0%B8-%D0%B2-derby-%D0%B0%D0%BD%D0%B0%D0%BB%D0%BE%D0%B3-rpc)

**Comment by paradoxina** [comment]
если не сложно, да =)

**Comment by zag2art** [comment]
Я вечерком пример накидаю

**Comment by zag2art** [comment]
## Первый вариант:
Во въюхе:
```html
<a on-click="startTimer()">Start timer</a>
```
Обработчик в компоненте
```js
MainPage.prototype.startTimer = function(){
  this.app.model.channel.send('startTimer', {});
};
```
На сервере, там где доступен `store`:
```js
store.on('client', function(client) {
  // Для каждого нового клиента, при подключении клиента
  client.channel.on('startTimer', function(data) {
    setTimeout(function(){
      // Здесь код отложенной задачи
    }, 1000)
  });
});
```

## Второй вариант:
Во въюхе:
```html
<a on-click="startTimer()">Start timer</a>
```
Обработчик в компоненте
```js
MainPage.prototype.startTimer = function(){
  // Используем ajax из jquery
  $.post('/api/start-timer', {});
};
```
На сервере, в express-мидлварах:
```js
var express = require('express');

var router = express.Router();

router.post('/api/start-timer', function(req, res){
  var model = req.getModel();
  setTimeout(function(){
    // Здесь код отложенной задачи

  }, 1000);
  res.json(true);
});

// ...
// В экспрессовских мидлварах роутер должен подключаться как-то так:

expressApp.use(router);

```

**Comment by paradoxina** [comment]
Спасибо Артур за помощь, ждем от Вас и Владимира новых примеров. что нибудь посерьезней и посложнее =))

**Comment by zag2art** [comment]
Если есть какие-нибудь мысли о том, что это могло бы быть за приложение - говорите, а то у меня что-то нет ярких идей.

**Comment by paradoxina** [comment]
Я не знаю как остальные, но хочется получше понимать как работает дерби, вот допустим код выше я бы узнал где нибудь через полгодика после тонны мануалов, так как nodejs и вообще серверный js  для меня новинка, не говоря про сотни разных модулей, которые надо понимать как работают. Многое объяснил курс Ильи Кантора, за что ему огромное спасибо. Я считаю на дерби создавать странички и большие веб приложения удобнее и быстрее чем писать с 0 на php, благодаря вашим примерам обучение проходит довольно быстро. На данный момент мой тестовый проект превратился из 2 страниц в 10 если не сотни шаблонов, страниц и даже несколько приложений. Работает я бы  не сказал что быстро, а скорей мгновенно. А реактивные функции это нечто, вкусняшка одним словом, разработка превращается в удовольствие.  Так вот , хочется представлять внутреннюю работу, а не писать не понимая что пишешь. Я понимаю что это все работает на отдельных модулях. и для каждого есть свой мануал, но хотя бы представление. Так же хочется поподробней узнать о правах доступа и как с ними быть. Хочется знать уязвимости и как  с ними бороться. Как использовать другую бд... ну и пожалуй пока хватит =)

**Comment by paradoxina** [comment]
А как получить доступ к модели из таймера?

**Comment by zag2art** [comment]
> А как получить доступ к модели из таймера?

В первом примере: `var model = store.createModel();`, во втором: `var model = req.getModel();`, но не забудьте, что если вы хотите менять какие-то данные, вам сначала нужно их подтянуть, например так:
```js
setTimeout(function(){
  var model = store.createModel();
  var myUserQuery = model.query('users', {email: 'zag2art@gmail.com'});

  model.fetch(myUserQuery, function(){
    var user = myUserQuery.get()[0];
    if (user){
      // Мы сделали fetch до того как делать set
      model.set('users.'+user.id+'.name', 'New Name');
    }
  });
}, 1000)
```

**Comment by zag2art** [comment]
Кстати:

> Так вот , хочется представлять внутреннюю работу, а не писать не понимая что пишешь.

А что вызывает наибольшее затруднение? Какие области не понятны?

**Comment by paradoxina** [comment]
Спасибо за код, все работает отлично. А насчет вопросов, подумаю, не хочется лишний раз беспокоить и спрашивать ерунду =)
