### ISSUE TITLE
Серверное время в  _session.time

### ISSUE THREAD

**Issue by paradoxina** [derbyparty/derby-faq#40]
Добрый день.
Мне нужно чтобы в локальной переменной  находилось актуальное серверное время, чтобы в дальнейшем с ним работать.  Как мне поместить серверное время Date().getTime() в _session.time ?. так же нужно обновление на стороне сервера по setInterval

**Comment by zag2art** [comment]
А зачем нужно время? В базу данных должно попадать? Или как? Просто есть несколько подходов, разные варианты, в зависимости от того, для чего это нужно.

**Comment by paradoxina** [comment]
допустим в шаблоне выводится определенное время от какой то точки отсчета {{_session.time - _page.time}}, в _page.time находится определенный stamp. Пробовал 
```
app.proto.init = function (){
  var model = this.model;
  if (derby.util.isServer) {    
    setInterval(function(){
    model.set('_session.time',new Date().getTime())      
    },100);
  }
```
но дело в том то при каждом обновлении страницы интервалы плодятся

**Comment by zag2art** [comment]
Не, опиши что ты хочешь при помощи всего этого СДЕЛАТЬ. То-есть вопрос именно в цели, что ты хочешь в итоге получить? Как будешь это время использовать?

**Comment by paradoxina** [comment]
Допустим время нажатия определенной кнопки. Когда пользователь нажал кнопку в stamp в базе должно записаться время нажатия (по серверу) а потом выводить время "кнопка нажата 20 секунд назад" , секунды соответственно меняются. Как то так

**Comment by zag2art** [comment]
Понятно, делается это так:

1. Запись серверного времени в коллекцию делается с помощью серверных хуков. Схема такая, в  приложении (на клиенте) в коллекцию просто записывается документ без даты создания, далее, на сервере срабатывает хук на создание документа, в котором дата дописывается в него. Благодаря реактивности эта дата сразу же появляется и на клиенте.

Для всего этого используется модуль - [derby-hook](https://github.com/derbyparty/derby-hook)

```js
// На сервере, там где доступен store

// подключаем derby-hook
var derbyHook = require('derby-hook');
derbyHook(store);

// ставим хук на создание
store.hook('create', 'items', function(docId) {
    model = store.createModel();
    $item = model.at('items.' + docId);

    model.fetch ($item, function(err){
      var timestamp = +new Date();
      $item.set('createdAt', timestamp);
    });
  });
```

Чуток попозже покажу, как на клиенте показывать все это дело в формате а ля "кнопка нажата 20 секунд назад", периодически обновляя. Для этого я использую модуль momentjs

**Comment by zag2art** [comment]
Обновляем глобальный таймер каждые 5 секунд:

```js
app.proto.create = function(){
  setInterval(updateTimer, 5000);

  function updateTimer(){
    model.set('_session.timer', +new Date());
  }
}
```
Вью-функция форматирования:

```js
var moment=require('moment');

app.proto.formatTime = function(time){
  // Возвратит текст, типа "a minute ago"
  return moment(time).fromNow();
}
```

Используем все это во вьюхе:

```html
  {{each items as #item}}
    <!-- ... -->
    <span>{{unescaped formaiTime(#item.createdAt, _session.timer)}}</span>
    <!-- ... -->
  {{/}}
```

В последнем пункте 2 особенности:

1. использовано служебное слово `unescaped` - это хак, позволяющий избежать ошибки при серверном рендеринге. Если например, сервер при рендеринге сгенерил текст "меньше минуты назад", страничка загрузилась (прошла какая-то доля секунды) и при атачинге текст уже превращается в "минуту назад" - то-есть текст различается. И если бы не было `unescaped` - то дерби бы выдало сообщение - "ошибка атачинга".
2. вторым параметром в функцию форматирования мы передали `_session.timer` - этот таймер будет каждые 5 секунд меняться, а значит и функция будет перезапускаться каждые 5 секунд. Очень удобно, хотя значение этого таймера мы внутри даже не используем.

**Comment by paradoxina** [comment]
хм, насколько я понимаю 
```js
app.proto.create = function(){
  setInterval(updateTimer, 5000);

  function updateTimer(){
    model.set('_session.timer', +new Date());
  }
}
```

срабатывает только на клиенте, значит и время будет в _session.timer клиентское. Время вывода времени может получится отрицательным, так как у клиента и сервера будет разное (в stamp серверное в _session.timer клиентское). Насколько я понял.

**Comment by zag2art** [comment]
Ну смотри, во-первых нам абсолютно не важно, что мы записываем в `_session.timer` - потому что мы это значение нигде не используем (нам важно лишь событие, которое возникает раз в 5 сек, то-есть с тем же успехом будет работать код - `model.set('_session.timer', true);`).

Во-вторых, нужно правильно понимать природу timestamp - если клиент и сервер синхронизированы, то таймстамп и там и там будет одинаковым (даже если сервер и клиент находятся в разных чаосвых поясах). Обычно они не очень синхронизированы - их время на несколько секунд может расходиться, но этим можно пренебречь (по крайней мере я так делаю, тот же самый github так делает и т.д.).

**Comment by zag2art** [comment]
Юникстайм в википедии определяется, как количество секунд, прошедших с полуночи (00:00:00 UTC) 1 января 1970 года (четверг); время с этого момента называют «эрой UNIX» (англ. Unix Epoch).

Это количество секунд одинаковое, что на клиенте, что на сервере - где бы они не находились. А таймстамп - это тот же юникстайм, но не в секундах, а в миллисекундах.

**Comment by paradoxina** [comment]
понял, тогда получается каждые 5 секунд на сервере идет перезапись в базу stamp. а мне надо допустим каждую секунду, а если пользователей будет больше 1000 + таких событий будет от каждого клиента около 50 получается 50 000 раз в секунду будет происходить перезапись в базе 
```js
$item.set('createdAt', timestamp);
```
как то накладно получается

до этого я делал так 

```js
app.proto.init = function (){
  var model = this.model;
//у каждого клиента в _session.time лежит именно серверное время, и таймер срабатывает только на сервере
  if (derby.util.isServer) {    
      setInterval(function(){
      model.set('_session.time',new Date().getTime())      
    },100);
  }
};
```

```js
app.proto.button1 = function (data){
  var model = this.model;
  //тут клиент берет именно stamp серверного времени
  var time_stamp = model.get('_session.time');
 model.set('items.item.data',data);
 model.set('items.item.time_stamp',time_satmp);
}

```

а в шаблоне делал так 
```html
<span>Прошло времени с последней записи {{timePars(_session_time - items.item.time_stamp)}}</span>
```

Все работает великолепно, но каждый раз при обновлении страницы запускается новый таймер.

Вот бы функция app.proto.create срабатывала не только на клиенте но и на сервере тогда бы проблема решилась

**Comment by paradoxina** [comment]
>Это количество секунд одинаковое, что на клиенте, что на сервере - где бы они не находились. А >таймстамп - это тот же юникстайм, но не в секундах, а в миллисекундах

хм, я не вникал в подробности но мне кажется если клиент переведет время начнется катавасия, и все рано клиенту нельзя доверять использовать свою Data()

**Comment by zag2art** [comment]
Думаю, есть определенное недопонимание того, как вот это работает
```js
    if (derby.util.isServer) {    
      setInterval(function(){
      model.set('_session.time',new Date().getTime())      
    },100);
  }
```

Что ожидается в `_session.time` ? текущее серверное время? или серверное время, которое там было в момент, когда вы получили бандл с сервера?

**Comment by zag2art** [comment]
> Все работает великолепно, но каждый раз при обновлении страницы запускается новый таймер

что подразумевается под "обновлении страницы"? жесткий f5? или переход между страницами внутри одного приложения?

**Comment by zag2art** [comment]
Вообще, на всяких случай отмечу, что `_session.time` с сервера на клиент попадает только один раз, и в базе данных не храниться и на клиенте обновиться и поменяться (с тем кодом, который ты показал сверху) не может. Попадает в момент серверного рендеринга.

**Comment by zag2art** [comment]
Коллекции, чье имя начинается с "_" не синхронизируются.

**Comment by droganov** [comment]
Простите, что вмешиваюсь, но контекст задачи плохо объяснен. Вывести актуальное время с сервера не так-то просто, пока информация о замере времени доходит до клиента, она как бы становится неактуальной. Попробуйте получить ее через какой-нибудь медленный азиатский прокси например и 10 МС назад, запросто превратится в 10 С назад.

Я не вижу где объяснено, зачем требуется передавать этот штамп с сервера. Если нужно показать пользователю как давно он нажал кнопку то зачем нужно что-то передавать на сервер и при чем здесь вообще интервал? Запишите в куку или в локалстор.

```
if (derby.util.isServer) {    
      setInterval(function(){
      model.set('_session.time',new Date().getTime())      
    },100);
  }
```
Этот код обеспечит 10 транзакций клиент-сервер в секунду. Зачем? Как много сессий вы хотите обслуживать единовременно?

Затем:
```
app.proto.button1 = function (data){
  var model = this.model;
  //тут клиент берет именно stamp серверного времени
  var time_stamp = model.get('_session.time');
 model.set('items.item.data',data);
 model.set('items.item.time_stamp',time_satmp);
}
```
Для чего требуется передавать на сервер штамп который уже известен серверу? В чем прикол?

**Comment by paradoxina** [comment]
Спасибо Артур,  вы пролили свет на мое недопонимание.
> Простите, что вмешиваюсь, но контекст задачи плохо объяснен

я согласен, но это из за плохого понимания работы сервера и клиента + плохие базовые знания. Артур верно меня понял и пояснил  как правильно делается то что я хочу. Задача отслеживать на сервере время выполнения задачи клиентом исходя из серверного времени. И не важно где находится клиент, хоть в Антарктиде, клиент сам должен понимать что такое пинг до сервера. А если нужна синхронность то тут идет вычисление пинга и так далее... но это другая история.
> Этот код обеспечит 10 транзакций клиент-сервер в секунду 

понимая это и встал данный вопрос, данный код был написан временно

Еще раз спасибо за помощь, вопрос я думаю закрыт
