### ISSUE TITLE
Как лучше хранить счетчики.

### ISSUE THREAD

**Issue by droganov** [derbyparty/derby-faq#41]
Привет.
Я задумал перевести приложение с экспресса на дерби и хочу посоветоваться. У меня есть список постов, у каждого поста есть счетчик просмотров. Лог просмотров мне не требуется, поэтому для меня OK хранить счетчик как `item.cnt.views`, соответсвенно при каждом просмотре сервер увеличивает (model.increment) значение счетчика. Кроме того я не хочу выносить счетчик в лог, потому что для вывода счетчика потребуется создавать лишнюю подписку.

Вроде бы все просто, но во-первых из доков не ясно как будет происходить синхронизация. При изменении поля, дерби перешлет подписчикам только новое значение поля или же весь `item`. Ожидаемо, что нужно передавать только значение поля, но уверенности нет.

Вторая проблема это индексция поисковиком. Мне бы хотелось использовать эластик ривер, но при более-менее приличной нагрузке эластик окажется загружен бессмысленной индексацией записей у которых обновился только счетчик, возможно кто-то уже сталкивался чем-то подобным и есть наработки? Кстати как у монго сейчас обстоят дела с поиском, он уже пригоден к использованию (стеммминг, производительность)?

**Comment by zag2art** [comment]
> дерби перешлет подписчикам только новое значение поля или же весь item

только новое значение

По остальному - не знаю, с эластиком не работал, с полнотекстовым поиском монги да, но больше года назад, были какие-то нарекания с морфологией, по-моему

**Comment by droganov** [comment]
Артур, спасибо!
