### ISSUE TITLE
Should I remove dom event listeners on component destroy event or not?

### ISSUE THREAD

**Issue by droganov** [derbyparty/derby-faq#45]
Hello.
It's not clear to me from the docs would derby care of dom event listeners or not.

Here is my case:
```
module.exports = class View
	view: __filename.replace /\.[^\.]+$/, ""
	create: (model, dom) ->
		model.setNull "ripples", []
		dom.on "mousedown", @container.parentNode, (ev) =>
			@push ev.layerX, ev.layerY
			delay 100, => @shift() if ev.button
			dom.once "mouseup", (ev) =>
				return unless model.get "current"
				@shift()
				ev.stopPropagation()
```

I suspect that I have to remove the listener manually, but the thing is that derby doesn't pass `dom` object to `destroy`method.

**Comment by cray0000** [comment]
nope, you don't need to remove them manually. Listeners that you create using `dom` object are being removed automatically on destroy.

**Comment by droganov** [comment]
Pavel, thank you!
